### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bketelsen** [WSU-ACM/askeecs#3]
This looks interesting, but without a license, many will be unwilling or afraid to use it or contribute.  Consider adding one?

**Comment by doingweb** [comment]
I agree. Also if it was owned by an organization (e.g., "wsu-eecs"), it would feel more like a community project than a personal one.

**Comment by whyrusleeping** [comment]
Yeah, Ill put it up under an MIT license. As far as an organization, the best i can do is the WSU-ACM, that sound alright @doingweb ?

**Comment by doingweb** [comment]
:+1:

**Comment by whyrusleeping** [comment]
Alright, license added and repo transferred to the ACM's org. now hopefully it garners some more attention by people with more free time than myself ;)
